# buildspec.yml
version: alpha
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run start
  cache:
    paths:
      - 'node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
      - '.next/cache/**/*' # Cache Next.js for faster application rebuilds